# Generated by Django 5.1.3 on 2024-11-17 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('first_name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(3, message='Debe tener por lo menos 3 caracteres')], verbose_name='nombre(s)')),
                ('last_name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(3, message='Debe tener por lo menos 3 caracteres')], verbose_name='apellido(s)')),
                ('document_type', models.CharField(blank=True, choices=[('CC', 'C.C. Cédula de ciudadanía'), ('NIT', 'NIT')], max_length=5, verbose_name='tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=12, verbose_name='número documento')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('-id',),
            },
        ),
    ]
