# Generated by Django 5.1.3 on 2024-11-20 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Solo números'), django.core.validators.MinLengthValidator(10)], verbose_name='número celular'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.CharField(max_length=12, verbose_name='número documento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(choices=[('CC', 'C.C. Cédula de ciudadanía'), ('NIT', 'NIT')], max_length=5, verbose_name='tipo de documento'),
        ),
    ]
