# Generated by Django 5.1.3 on 2024-11-20 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Solo números'), django.core.validators.MinLengthValidator(10)], verbose_name='número de teléfono'),
            preserve_default=False,
        ),
    ]
