# Generated by Django 5.1.3 on 2024-11-19 01:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('iva', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='porcentaje IVA')),
                ('has_iva', models.BooleanField(verbose_name='tiene IVA')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(max_length=128, unique=True, verbose_name='consecutivo')),
                ('date', models.DateField(verbose_name='fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de creación')),
                ('subtotal', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal')),
                ('iva', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='iva')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('iva', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor IVA')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.product', verbose_name='producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'producto vendido',
                'verbose_name_plural': 'productos vendidos',
                'ordering': ('-id',),
            },
        ),
    ]
