# Generated by Django 5.1.3 on 2024-11-19 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_product_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad'),
            preserve_default=False,
        ),
    ]
