# Generated by Django 5.1.3 on 2024-11-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_saleproduct_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='code',
            field=models.CharField(max_length=128, verbose_name='codigo'),
        ),
    ]
