# Generated by Django 5.1.3 on 2024-11-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_saleproduct_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_iva',
        ),
    ]
