# Generated by Django 5.1.3 on 2024-11-17 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('first_name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(3, message='Debe tener por lo menos 3 caracteres')], verbose_name='nombre(s)')),
                ('last_name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(3, message='Debe tener por lo menos 3 caracteres')], verbose_name='apellido(s)')),
                ('document_type', models.CharField(blank=True, choices=[('CC', 'C.C. Cédula de ciudadanía'), ('NIT', 'NIT')], max_length=5, verbose_name='tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=12, verbose_name='número documento')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si puede entrar al sitio de administración.', verbose_name='staff')),
                ('is_active', models.BooleanField(default=False, help_text='Indica si el usuario puede ingresar a la plataforma.', verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ('-id',),
            },
        ),
    ]
